### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VuongVy** [alexzvn/oraxen#1]
```
[15:54:09 WARN]: [io.th0rgal.oraxen.OraxenPlugin] [Oraxen] <gradient:#9055FF:#13E2DA>Oraxen <#282B3F>|  Task #27 for Oraxen v1.119.0 generated an exception
java.lang.Error: Furniture Mechanic not found at location: Location{world=CraftWorld{name=world},x=-262.5,y=72.03125,z=-109.5,pitch=-90.0,yaw=0.0}
        at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.evolution.EvolutionTask.runEachFrame(EvolutionTask.java:57) ~[oraxen-1.119.0-all.jar:?]
        at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.evolution.EvolutionTask.run(EvolutionTask.java:35) ~[oraxen-1.119.0-all.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by VuongVy** [comment]
30~50 minutes after grow seeds, console spam this error

**Comment by alexzvn** [comment]
@VuongVy next time, consider use Pastebin to store log

**Comment by alexzvn** [comment]
3 bugs relative to item frame confirmed

**Comment by alexzvn** [comment]
Fixed
